In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../../../../datasets/predict_moview_ratings/train_v2.csv')

In [3]:
df.head()

ID  user  movie  rating
0  610739  3704   3784       3
1  324753  1924    802       3
2  808218  4837   1387       4
3  133808   867   1196       4
4  431858  2631   3072       5

In [4]:
import torch
import torch.nn as nn

In [7]:
a = torch.rand(5,2)

In [8]:
a

tensor([[0.3857, 0.4920],
        [0.3925, 0.4585],
        [0.5825, 0.4938],
        [0.0319, 0.8320],
        [0.9395, 0.6965]])

In [9]:
b = torch.rand(5,2)

In [10]:
b

tensor([[0.3869, 0.6041],
        [0.1251, 0.5901],
        [0.3497, 0.8315],
        [0.5580, 0.8106],
        [0.4460, 0.2017]])

In [11]:
torch.cat([a, b], dim=-1)

tensor([[0.3857, 0.4920, 0.3869, 0.6041],
        [0.3925, 0.4585, 0.1251, 0.5901],
        [0.5825, 0.4938, 0.3497, 0.8315],
        [0.0319, 0.8320, 0.5580, 0.8106],
        [0.9395, 0.6965, 0.4460, 0.2017]])

In [15]:
from sklearn import model_selection
def encode_data(df, train=None):
    """ Encodes rating data with continous user and movie ids. 
    If train is provided, encodes df with the same encoding as train.
    """
    df = df.copy()
    len_encoding = []
    for col_name in ["user", "movie"]:
        train_col = None
        if train is not None:
            train_col = train[col_name]
        _,col,len_uniq = proc_col(df[col_name], train_col)
        df[col_name] = col
        df = df[df[col_name] >= 0]
        len_encoding.append(len_uniq)
    return df,len_encoding
def proc_col(col, train_col=None):
    """Encodes a pandas column with continous ids. 
    """
    if train_col is not None:
        uniq = train_col.unique()
    else:
        uniq = col.unique()
    name2idx = {o:i for i,o in enumerate(uniq)}
    return name2idx, np.array([name2idx.get(x, -1) for x in col]), len(uniq)


df = pd.read_csv('../../../../datasets/predict_moview_ratings/train_v2.csv')

df_train,df_valid = model_selection.train_test_split(df,test_size = 0.1, random_state = 42,stratify = df.rating.values)
df_train,len_encoding = encode_data(df_train)
# df_valid,_ = encode_data(df_valid,df_train)

# train_ds = moviedataset(df_train)
# valid_ds = moviedataset(df_valid)
# train_dl = DataLoader(train_ds,batch_size = congif['batch_size'],shuffle=True)
# valid_dl = DataLoader(valid_ds,batch_size = congif['batch_size'])
print(len_encoding[0],len_encoding[1])

6040 3660
